sudo: false
language: perl
perl:
  - "dev"
  - "dev-thr"
  - "5.24"
  - "5.24.0-thr"
  - "5.22"
  - "5.22.0-thr"
  - "5.20"
  - "5.20.0-thr"
  - "5.18"
  - "5.18.0-thr"
  - "5.16"
  - "5.16.0-thr"
  - "5.14"
  - "5.14.0-thr"
  - "5.12"
  - "5.12.0-thr"
  - "5.10"
  - "5.10.0-thr"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto
